export const dummy = {
  숙소: [
    {
      contentId: 11,
      name: "숙소1",
      address: "서울특별시 송파구",
      imageUrl: "https://loremflickr.com/270/370/kitty",
    },
    {
      contentId: 12,
      name: "숙소2",
      address: "서울특별시 마포구",
      imageUrl: "https://loremflickr.com/270/370/tiger",
    },
    {
      contentId: 13,
      name: "숙소3",
      address: "서울특별시 종로구",
      imageUrl: "https://loremflickr.com/270/370/cat",
    },
    {
      contentId: 14,
      name: "숙소4",
      address: "서울특별시 강남구",
      imageUrl: "https://loremflickr.com/270/370/dog",
    },
    {
      contentId: 15,
      name: "숙소5",
      address: "서울특별시 강북구",
      imageUrl: "https://loremflickr.com/270/370/panda",
    },
    {
      contentId: 16,
      name: "숙소6",
      address: "서울특별시 서초구",
      imageUrl: "https://loremflickr.com/270/370/puppy",
    },
    {
      contentId: 17,
      name: "숙소7",
      address: "서울특별시 은평구",
      imageUrl: "https://loremflickr.com/270/370/korea",
    },
    {
      contentId: 18,
      name: "숙소8",
      address: "서울특별시 동작구",
      imageUrl: "https://loremflickr.com/270/370/home,7",
    },
    {
      contentId: 19,
      name: "숙소9",
      address: "서울특별시 관악구",
      imageUrl: "https://loremflickr.com/270/370/home,8",
    },
    {
      contentId: 20,
      name: "숙소10",
      address: "서울특별시 노원구",
      imageUrl: "https://loremflickr.com/270/370/home,9",
    },
  ],
  맛집: [
    {
      contentId: 1,
      name: "맛집1",
      address: "서울특별시 강남구",
      imageUrl: "https://loremflickr.com/270/370/bread",
    },
    {
      contentId: 2,
      name: "맛집2",
      address: "서울특별시 강북구",
      imageUrl: "https://loremflickr.com/270/370/coffee",
    },
    {
      contentId: 3,
      name: "맛집3",
      address: "서울특별시 서대문구",
      imageUrl: "https://loremflickr.com/270/370/sushi",
    },
    {
      contentId: 4,
      name: "맛집4",
      address: "서울특별시 용산구",
      imageUrl: "https://loremflickr.com/270/370/meat",
    },
    {
      contentId: 5,
      name: "맛집5",
      address: "서울특별시 성동구",
      imageUrl: "https://loremflickr.com/270/370/hamburger",
    },
    {
      contentId: 6,
      name: "맛집6",
      address: "서울특별시 마포구",
      imageUrl: "https://loremflickr.com/270/370/pork",
    },
    {
      contentId: 7,
      name: "맛집7",
      address: "서울특별시 중구",
      imageUrl: "https://loremflickr.com/270/370/pasta",
    },
    {
      contentId: 8,
      name: "맛집8",
      address: "서울특별시 동작구",
      imageUrl: "https://loremflickr.com/270/370/coffee",
    },
    {
      contentId: 9,
      name: "맛집9",
      address: "서울특별시 강서구",
      imageUrl: "https://loremflickr.com/270/370/pizza",
    },
    {
      contentId: 10,
      name: "맛집10",
      address: "서울특별시 송파구",
      imageUrl: "https://loremflickr.com/270/370/cookie",
    },
  ],
  쇼핑: [
    {
      contentId: 21,
      name: "쇼핑몰1",
      address: "서울특별시 동대문구",
      imageUrl: "https://loremflickr.com/270/370/shopping",
    },
    {
      contentId: 22,
      name: "쇼핑몰2",
      address: "서울특별시 서대문구",
      imageUrl: "https://loremflickr.com/270/370/shopping",
    },
    {
      contentId: 23,
      name: "쇼핑몰3",
      address: "서울특별시 광진구",
      imageUrl: "https://loremflickr.com/270/370/shopping",
    },
    {
      contentId: 24,
      name: "쇼핑몰4",
      address: "서울특별시 중구",
      imageUrl: "https://loremflickr.com/270/370/shopping",
    },
    {
      contentId: 25,
      name: "쇼핑몰5",
      address: "서울특별시 종로구",
      imageUrl: "https://loremflickr.com/270/370/shopping",
    },
    {
      contentId: 26,
      name: "쇼핑몰6",
      address: "서울특별시 성북구",
      imageUrl: "https://loremflickr.com/270/370/shopping",
    },
    {
      contentId: 27,
      name: "쇼핑몰7",
      address: "서울특별시 강남구",
      imageUrl: "https://loremflickr.com/270/370/shopping",
    },
    {
      contentId: 28,
      name: "쇼핑몰8",
      address: "서울특별시 강북구",
      imageUrl: "https://loremflickr.com/270/370/shopping",
    },
    {
      contentId: 29,
      name: "쇼핑몰9",
      address: "서울특별시 관악구",
      imageUrl: "https://loremflickr.com/270/370/shopping",
    },
    {
      contentId: 30,
      name: "쇼핑몰10",
      address: "서울특별시 노원구",
      imageUrl: "https://loremflickr.com/270/370/shopping",
    },
  ],
  문화: [
    {
      contentId: 31,
      name: "문화공간1",
      address: "서울특별시 강동구",
      imageUrl: "https://loremflickr.com/270/370/culture",
    },
    {
      contentId: 32,
      name: "문화공간2",
      address: "서울특별시 성동구",
      imageUrl: "https://loremflickr.com/270/370/culture",
    },
    {
      contentId: 33,
      name: "문화공간3",
      address: "서울특별시 강남구",
      imageUrl: "https://loremflickr.com/270/370/culture",
    },
    {
      contentId: 34,
      name: "문화공간4",
      address: "서울특별시 중랑구",
      imageUrl: "https://loremflickr.com/270/370/culture",
    },
    {
      contentId: 35,
      name: "문화공간5",
      address: "서울특별시 도봉구",
      imageUrl: "https://loremflickr.com/270/370/culture",
    },
    {
      contentId: 36,
      name: "문화공간6",
      address: "서울특별시 노원구",
      imageUrl: "https://loremflickr.com/270/370/culture",
    },
    {
      contentId: 37,
      name: "문화공간7",
      address: "서울특별시 구로구",
      imageUrl: "https://loremflickr.com/270/370/culture",
    },
    {
      contentId: 38,
      name: "문화공간8",
      address: "서울특별시 양천구",
      imageUrl: "https://loremflickr.com/270/370/culture",
    },
    {
      contentId: 39,
      name: "문화공간9",
      address: "서울특별시 서대문구",
      imageUrl: "https://loremflickr.com/270/370/culture",
    },
    {
      contentId: 40,
      name: "문화공간10",
      address: "서울특별시 마포구",
      imageUrl: "https://loremflickr.com/270/370/culture",
    },
  ],
};
