name: Deploy to Server

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v3
        with:
          ref: develop

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Yarn
        run: curl -o- -L https://yarnpkg.com/install.sh | bash

      - name: Add Yarn to PATH
        run: echo "$HOME/.yarn/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: yarn install

      - name: Copy .env File
        run: cp /home/mschoi/Desktop/tourismContest/Yaguhang-FE/.env /home/mschoi/actions-runner-FE/_work/Yaguhang_FE/Yaguhang_FE

      - name: Build project
        run: yarn build

      - name: Replace old build with new build
        run: |
          rm -rf /home/mschoi/Desktop/tourismContest/Yaguhang-FE/dist
          cp -r ./dist /home/mschoi/Desktop/tourismContest/Yaguhang-FE/

      - name: Set proper permissions for Nginx
        run: |
          sudo chmod -R o+r /home/mschoi/Desktop/tourismContest/Yaguhang-FE/dist
          sudo find /home/mschoi/Desktop/tourismContest/Yaguhang-FE/dist -type d -exec chmod o+x {} \;
